<?php
/**
 * MetricValueTest
 *
 * PHP version 7.1
 *
 * @category Class
 * @package  GenericApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Generic API
 *
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GenericApi\Client;

use PHPUnit\Framework\TestCase;

/**
 * MetricValueTest Class Doc Comment
 *
 * @category    Class
 * @description MetricValue
 * @package     GenericApi\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MetricValueTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MetricValue"
     */
    public function testMetricValue()
    {
    }

    /**
     * Test attribute "metricId"
     */
    public function testPropertyMetricId()
    {
    }

    /**
     * Test attribute "valueString"
     */
    public function testPropertyValueString()
    {
    }

    /**
     * Test attribute "valueNumber"
     */
    public function testPropertyValueNumber()
    {
    }

    /**
     * Test attribute "valueMin"
     */
    public function testPropertyValueMin()
    {
    }

    /**
     * Test attribute "valueMax"
     */
    public function testPropertyValueMax()
    {
    }

    /**
     * Test attribute "valueAvg"
     */
    public function testPropertyValueAvg()
    {
    }

    /**
     * Test attribute "valueSum"
     */
    public function testPropertyValueSum()
    {
    }

    /**
     * Test attribute "createdTs"
     */
    public function testPropertyCreatedTs()
    {
    }
}
