<?php
/**
 * MetricApiTest
 * PHP version 7.1
 *
 * @category Class
 * @package  GenericApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Generic API
 *
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GenericApi\Client;

use \GenericApi\Client\Configuration;
use \GenericApi\Client\ApiException;
use \GenericApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MetricApiTest Class Doc Comment
 *
 * @category Class
 * @package  GenericApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MetricApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getMetric
     *
     * Получение данных метрики.
     *
     */
    public function testGetMetric()
    {
    }

    /**
     * Test case for metricsHistory
     *
     * Получение истории измерений метрик.
     *
     */
    public function testMetricsHistory()
    {
    }

    /**
     * Test case for metricsLastValues
     *
     * Получение последних измерений.
     *
     */
    public function testMetricsLastValues()
    {
    }

    /**
     * Test case for searchMetrics
     *
     * Поиск метрик объектов.
     *
     */
    public function testSearchMetrics()
    {
    }
}
